# Generated by Django 5.1.1 on 2024-11-05 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('adultomayor', 'Adulto mayor'), ('prestador', 'Profesional')], max_length=30)),
                ('estado_solicitud', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=25)),
                ('primer_nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=25, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=25, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=128)),
                ('contacto', models.CharField(default='Sin contacto', max_length=20, unique=True)),
                ('calle', models.CharField(default='CalleDesconocida', max_length=25)),
                ('num_casa', models.CharField(blank=True, max_length=50, null=True)),
                ('num_apar', models.CharField(blank=True, max_length=50, null=True)),
                ('admin', models.BooleanField(default=False)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'permissions': [('can_view_sensitive_data', 'Puede ver datos sensibles')],
            },
        ),
        migrations.CreateModel(
            name='Centro_Comunitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_centro', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Para_Graficos',
            fields=[
                ('id_consultas', models.AutoField(primary_key=True, serialize=False)),
                ('fechas', models.DateField()),
                ('horas', models.TimeField()),
                ('t_consulta', models.CharField(blank=True, max_length=100, null=True)),
                ('genero_persona', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(default='ApellidoDesconocido', max_length=100)),
                ('contrasena', models.CharField(blank=True, max_length=128)),
                ('contacto', models.CharField(default='Sin contacto', max_length=20, unique=True)),
                ('servicio', models.CharField(max_length=30)),
                ('calle', models.CharField(default='CalleDesconocida', max_length=25)),
                ('num_casa', models.CharField(max_length=50)),
                ('num_apar', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AdultoMayor',
            fields=[
                ('rut', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('peluqueriaBloqueo', models.DateField(blank=True)),
                ('podologiaBloqueo', models.DateField(blank=True)),
                ('kinesiologiaBloqueo', models.DateField(blank=True)),
                ('psicologiaBloqueo', models.DateField(blank=True)),
                ('asesoria_juridicaBloqueo', models.DateField(blank=True)),
                ('fonoaudiologiaBloqueo', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultas_Agendadas',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('servicio', models.CharField(blank=True, max_length=30)),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
                ('rut_prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prestador')),
            ],
        ),
    ]
