# Generated by Django 5.1.1 on 2024-11-22 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('rut', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('adultomayor', 'Adulto mayor'), ('prestador', 'Profesional')], max_length=30)),
                ('estado_solicitud', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=25)),
                ('primer_nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('segundo_nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=25, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=25, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=128)),
                ('contacto', models.CharField(default='Sin contacto', max_length=20, unique=True)),
                ('calle', models.CharField(default='CalleDesconocida', max_length=25)),
                ('num_casa', models.CharField(blank=True, max_length=50, null=True)),
                ('num_apar', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('can_view_sensitive_data', 'Puede ver datos sensibles')],
            },
        ),
        migrations.CreateModel(
            name='Centro_Comunitario',
            fields=[
                ('id_centro', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('rut', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('adultomayor', 'Adulto mayor'), ('prestador', 'Profesional')], default='adultomayor', max_length=30)),
                ('estado_solicitud', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Para_Graficos',
            fields=[
                ('id_consultas', models.AutoField(primary_key=True, serialize=False)),
                ('fechas', models.DateField()),
                ('horas', models.TimeField()),
                ('t_consulta', models.CharField(blank=True, max_length=100, null=True)),
                ('genero_persona', models.CharField(blank=True, max_length=100, null=True)),
                ('asistencia', models.CharField(blank=True, max_length=2, null=True)),
                ('consultorio', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('nombre_servicio', models.CharField(choices=[('peluqueria', 'Peluqueria'), ('podologia', 'Podologia'), ('kinesiologia', 'Kinesiologia'), ('psicologia', 'Psicologia'), ('asesoria_juridica', 'Asesoria Juridica'), ('fonoaudiologia', 'Fonoaudiologia')], max_length=50, primary_key=True, serialize=False, unique=True)),
                ('tiempo_atencion', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AdultoMayor',
            fields=[
                ('rut', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('peluqueriaBloqueo', models.DateField(blank=True, default=None, null=True)),
                ('podologiaBloqueo', models.DateField(blank=True, default=None, null=True)),
                ('kinesiologiaBloqueo', models.DateField(blank=True, default=None, null=True)),
                ('psicologiaBloqueo', models.DateField(blank=True, default=None, null=True)),
                ('asesoria_juridicaBloqueo', models.DateField(blank=True, default=None, null=True)),
                ('fonoaudiologiaBloqueo', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario_Prestadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('hora_termino', models.TimeField()),
                ('descanso', models.TimeField()),
                ('rut_prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prestador')),
            ],
        ),
        migrations.CreateModel(
            name='Consultas_Agendadas',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_termino', models.TimeField(blank=True, null=True)),
                ('servicio', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rut_prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prestador')),
            ],
        ),
        migrations.AddField(
            model_name='prestador',
            name='servicio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.servicios'),
        ),
    ]
