# Generated by Django 5.1.1 on 2024-11-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adultomayor',
            name='asesoria_juridicaBloqueo',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='fonoaudiologiaBloqueo',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='kinesiologiaBloqueo',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='peluqueriaBloqueo',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='podologiaBloqueo',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='adultomayor',
            name='psicologiaBloqueo',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
