# Generated by Django 5.1.1 on 2024-11-22 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario_prestadores',
            name='descanso',
        ),
        migrations.RemoveField(
            model_name='horario_prestadores',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='horario_prestadores',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='horario_prestadores',
            name='hora_inicio',
        ),
        migrations.RemoveField(
            model_name='horario_prestadores',
            name='hora_termino',
        ),
        migrations.RemoveField(
            model_name='horario_prestadores',
            name='rut_prestador',
        ),
    ]
