# Generated by Django 5.1.1 on 2024-11-08 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas_agendadas',
            name='rut_prestador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.prestador'),
        ),
        migrations.AlterField(
            model_name='consultas_agendadas',
            name='rut_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
