# Generated by Django 5.1.1 on 2024-11-10 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_adultomayor_asesoria_juridicabloqueo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('nombre_servicio', models.CharField(choices=[('peluqueria', 'Peluqueria'), ('podologia', 'Podologia'), ('kinesiologia', 'Kinesiologia'), ('psicologia', 'Psicologia'), ('asesoria_juridica', 'Asesoria_Juridica'), ('fonoaudiologia', 'Fonoaudiologia')], max_length=100, primary_key=True, serialize=False, unique=True)),
                ('tiempo_atencion', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='prestador',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='prestador',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='prestador',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='prestador',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='prestador',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='prestador',
            name='num_apar',
        ),
        migrations.RemoveField(
            model_name='prestador',
            name='num_casa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='admin',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('adultomayor', 'Adulto mayor'), ('prestador', 'Profesional')], default='adultomayor', max_length=30),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='servicio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.servicios'),
        ),
    ]
