# Generated by Django 5.1.1 on 2024-11-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_servicios_remove_prestador_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_para_graficos',
            name='consultorio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
