# Generated by Django 5.1.1 on 2024-10-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usuario_rut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('can_view_sensitive_data', 'Puede ver datos sensibles')]},
        ),
        migrations.RemoveField(
            model_name='consultas_agendadas',
            name='hora_termino',
        ),
        migrations.RemoveField(
            model_name='consultas_agendadas',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_centro',
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultas_agendadas',
            name='id_consulta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='contrasena',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
