# Generated by Django 5.1.1 on 2024-10-01 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usuario_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('can_view_sensitive_data', 'Puede ver datos sensibles')]},
        ),
    ]
