# Generated by Django 5.1.1 on 2024-10-02 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_usuario_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultas_agendadas',
            name='servicio',
        ),
    ]
