# Generated by Django 5.1.1 on 2024-10-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_consultas_agendadas_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_centro',
        ),
    ]
