# Generated by Django 5.1.1 on 2024-10-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_usuario_id_centro'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas_agendadas',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
