# Generated by Django 5.1.1 on 2024-10-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usuario_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas_agendadas',
            name='servicio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
