# Generated by Django 5.1.1 on 2024-10-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_consultas_agendadas_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas_agendadas',
            name='servicio',
            field=models.CharField(default='Servicio temporal', max_length=50),
            preserve_default=False,
        ),
    ]
