# Generated by Django 5.1.1 on 2024-10-17 01:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_consultas_agendadas_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario_prestadores',
            name='dia',
            field=models.CharField(default='Lunes', max_length=15),
        ),
        migrations.AddField(
            model_name='horario_prestadores',
            name='hora_fin',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='horario_prestadores',
            name='rut_prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prestador'),
        ),
    ]
