# Generated by Django 5.1.1 on 2024-10-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_horario_prestadores_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas_agendadas',
            name='hora_termino',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='disponibilidad',
            field=models.JSONField(default=dict),
        ),
    ]
