# Generated by Django 5.1.1 on 2024-10-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_consultas_agendadas_hora_termino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestador',
            name='disponibilidad',
        ),
    ]
