# Generated by Django 5.1.1 on 2024-10-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_prestador_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario_prestadores',
            name='dia',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], max_length=15),
        ),
    ]
