# Generated by Django 5.1.1 on 2024-10-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_horario_prestadores_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas_agendadas',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
