# Generated by Django 5.1.1 on 2024-11-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_contrasena_usuario_password_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='max_session_duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usuario',
            name='session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
