# Generated by Django 5.1.1 on 2024-11-24 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_anticipacion', models.IntegerField(help_text='Tiempo en minutos antes de la cita para enviar el recordatorio.')),
                ('metodo', models.CharField(choices=[('email', 'Email'), ('notificacion', 'Notificación Push')], default='email', max_length=20)),
                ('mensaje', models.TextField(default='Recordatorio: Tienes una cita agendada.')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.consultas_agendadas')),
            ],
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
