# Generated by Django 5.1.1 on 2024-11-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_recordatorio_delete_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas_agendadas',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
